services:
  - type: web
    name: kati-export-helper
    env: python
    plan: free
    buildCommand: |
      # Python 패키지 설치 (간단한 버전)
      pip install -r requirements_simple.txt
    startCommand: python app_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true

    healthCheckPath: /
    autoDeploy: true 