services:
  - type: web
    name: kati-customs-system
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: IS_RENDER
        value: true
      - key: PORT
        value: 10000
    autoDeploy: true
    buildFilter:
      paths:
        - requirements.txt
        - app.py
        - "*.py"
        - templates/**
        - static/**
    healthCheckPath: /
    numInstances: 1 