services:
  - type: web
    name: kati-simple
    env: python
    buildCommand: pip install -r requirements_simple.txt
    startCommand: gunicorn app_simple:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 