name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests (if any)
      run: |
        echo "Running basic checks..."
        python -c "import app; print('App import successful')"
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Install EB CLI
      run: |
        pip install awsebcli
        
    - name: Deploy to EB
      run: |
        eb deploy kati-production --region ap-northeast-2
      env:
        EB_APP_NAME: kati-export-helper
        EB_ENV_NAME: kati-production
        
    - name: Health check
      run: |
        echo "Deployment completed. Checking health..."
        sleep 30
        curl -f ${{ secrets.EB_URL }} || echo "Health check failed" 